### ISSUE TITLE
isPlaying never set to false in iOS simulator

### ISSUE THREAD

**Issue by dbertella** [florent37/Flutter-AssetsAudioPlayer#171]
**Flutter Version**

My version : 
Flutter 1.19.0-2.0.pre • channel master • https://github.com/flutter/flutter.git
Framework • revision 1d395c5e18 (7 days ago) • 2020-05-31 07:41:50 -0700
Engine • revision 923687f0e7
Tools • Dart 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

**Lib Version**

My version : ^1.6.3

**Platform (Android / iOS / web) + version**

Platform : iOS

**Describe the bug**
I'm trying to show / hide some buttons when the music, in my case it's a voice reading a book stops. I implemented the StreamBuilder following the example in the documentation and it seemed to work in android (simulator) Today I was using iOS one and the buttons never appear in my scene while in android do. 

**Small code to reproduce**

```dart
  _assetsAudioPlayer.open(
      Audio('assets/audio.mp3'),
      autoStart: true,
      playInBackground: PlayInBackground.disabledRestoreOnForeground,
    );

...

return StreamBuilder(
    stream: _assetsAudioPlayer.isPlaying,
    builder: (context, asyncSnapshot) {
        final bool isPlaying = asyncSnapshot.data;
        return Text(isPlaying ? "Pause" : "Play");  
    }),
```

This is the link at the repo in case it can be useful https://github.com/dbertella/hector-app/blob/master/lib/Story.dart#L105

**Comment by florent37** [comment]
Ok I look :)

**Comment by florent37** [comment]
I reproduce, thanks for the issue, I fix it

**Comment by florent37** [comment]
I think i fixed it, can you try the `2.0.1+3` please ?

**Comment by dbertella** [comment]
You are actually amazing! I will try as soon as I get back to the computer.

**Comment by dbertella** [comment]
hey @florent37 I'm getting this error at the moment as soon as I open an audio file
```Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/daniele/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-2.0.1+3/ios/Classes/Music.swift, line 666```
> Line 666 🥶
And the app just crash still on the ios simulator

I run `flutter clean` already. Do you know what it can be?

**Comment by dbertella** [comment]
I have the same issue with version 2.0.1, I downgraded back to 1.6.3 and everything works fine

**Comment by florent37** [comment]
Ok I look
