### ISSUE TITLE
 assetsAudioPlayer.playlist.insert(index, audio) not work

### ISSUE THREAD

**Issue by liuchuancong** [florent37/Flutter-AssetsAudioPlayer#233]
etc

**Comment by liuchuancong** [comment]
```E/flutter (23087): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Only valid value is 0: -1
E/flutter (23087): #0      List.[]  (dart:core-patch/growable_array.dart:146:60)
E/flutter (23087): #1      _CurrentPlaylist.currentAudio 
package:assets_audio_player/src/assets_audio_player.dart:1382
E/flutter (23087): #2      AssetsAudioPlayer._openPlaylistCurrent 
package:assets_audio_player/src/assets_audio_player.dart:693
E/flutter (23087): #3      AssetsAudioPlayer.playlistPlayAtIndex 
package:assets_audio_player/src/assets_audio_player.dart:659
E/flutter (23087): #4      AudioInstance.playlistPlayAtIndex 
package:music/plugin/audio.dart:138
E/flutter (23087): #5      _MyHomePageState.build.<anonymous closure> 
package:music/main.dart:356
E/flutter (23087): #6      BackdropNavigationBackLayer.build.<anonymous closure>.<anonymous closure> 
package:backdrop/navigation.dart:76
E/flutter (23087): #7      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:779
E/flutter (23087): #8      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:862
E/flutter (23087): #9      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter (23087): #10     TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:504
E/flutter (23087): #11     BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:282
E/flutter (23087): #12     BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:254
E/flutter (23087): #13     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter (23087): #14     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter (23087): #15     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (23087): #16     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (23087): #17     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (23087): #18     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (23087): #19     _rootRunUnary  (dart:async/zone.dart:1196:13)
E/flutter (23087): #20     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (23087): #21     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter (23087): #22     _invoke1  (dart:ui/hooks.dart:275:10)
E/flutter (23087): #23     _dispatchPointerDataPacket  (dart:ui/hooks.dart:184:5)
E/flutter (23087):
I/flutter (23087): 3
```
assetsAudioPlayer.playlist.audios.length is 3;
_CurrentPlaylist just 1

**Comment by florent37** [comment]
Ok I try !

**Comment by florent37** [comment]
I fixed it, can you try `2.0.5+5` please ?

**Comment by liuchuancong** [comment]
```

_playerState:BehaviorSubject (Instance of 'BehaviorSubject<PlayerState>')
_playlist:_CurrentPlaylist
indexList:List (1 item)
loopMode:LoopMode (LoopMode.none)
notificationSettings:NotificationSettings
playInBackground:PlayInBackground (PlayInBackground.enabled)
playSpeed:null
playlist:Playlist
_currentlyOpenedIn:_CompactLinkedHashSet ({Instance of 'PlayerEditor'})
_startIndex:0
audios:List (3 items)
```

Thank you for your help.
The problem still exists.
the _playlist doesn't update

**Comment by liuchuancong** [comment]
```
assets_audio_player: ^2.0.5+7
```

**Comment by florent37** [comment]
can you try the file `https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_insert.dart`

does this sample work for you ?

**Comment by florent37** [comment]
and can you send me the part of your code where you 
1. use the `open` method
2. use the `insert` method 

please, it will help me a lot :)

**Comment by liuchuancong** [comment]
thanks! wait me a little time

**Comment by liuchuancong** [comment]
you are my hero!  it works!  

thanks for your time!

**Comment by florent37** [comment]
I don't understand, what did I changed between those two messages ? :)

**Comment by liuchuancong** [comment]
yestoday  i use this  assetsAudioPlayer.playlist.audios.insert(index, audio) 
and  forgot fixed it
